title: A blog mostly about Deep Learning
author: Pascal LEFEVRE
email: plefevre561@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  contents about deep learning, computer vision, mathematics, etc

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  pl561 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
